[project]
name = "comando-cli"
version = "0.1.0"
description = "Stream movies and TV series from gratistorrent.com via CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cloakbrowser>=0.3.18",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "requests>=2.32.5",
    "scrapling[all]>=0.4",
    "typer>=0.24.1",
    "yoyo-migrations>=9.0.0",
]

[project.scripts]
com = "comando_cli.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
